python/README.md

Testing my PR capability on this repo, and minor edits from installing and running ml4ir

Minor edits from trial install

---

python/.gitignore
python/.pre-commit-config.yaml
python/README.md
python/ml4ir/config/features.py
python/ml4ir/config/parse_args.py
python/ml4ir/data/tfrecord_reader.py
python/ml4ir/io/file_io.py
python/ml4ir/model/metrics/metric_factory.py
python/ml4ir/model/metrics/metrics_impl.py
python/ml4ir/model/pipeline.py
python/ml4ir/model/ranking_model.py
python/ml4ir/tests/data/csv/feature_config.json
python/ml4ir/tests/data/tfrecord/feature_config.json
python/ml4ir/tests/test_metrics.py
python/ml4ir/tests/test_serving.py
python/requirements.txt

This PR contains the following changes
- MRR, ACR validation metrics
- ~Functionality to compute additional group based aggregations on metrics~
- Writing old rank, new rank, new score for each record being ranked
- Unit tests for the above

Adding ranking validation metrics

---

jvm/ml4ir-inference/pom.xml
jvm/ml4ir-inference/src/main/java/ml4ir/inference/tensorflow/ModelFeaturesParser.java
jvm/ml4ir-inference/src/main/java/ml4ir/inference/tensorflow/utils/ModelFeatures.java
jvm/ml4ir-inference/src/test/java/ml4ir/inference/tensorflow/ModelFeaturesParserTest.java
jvm/ml4ir-inference/src/test/resources/model_features.yaml

- Adding yaml parser to read the important metadata related to features
- Adding a unit test to verify the extraction

Adding code to parse model config yaml file to extract feature metadata

---

.git2gus/config.json
LICENSE.txt

Add the Apache License 2.0 to the project.

add ASL2.0

---

python/README.md
python/requirements.txt
python/setup.py

- Updating setup.py to to process dependencies from requirements.txt
- Updated requirements.txt to remove '-e' as we don't want to install in develop mode
- Updated the ReadMe to specify on how to install this via github

Updating setup file for installing dependencies 

---

.circleci/config.yml

Initial setup for circleci - the config is copied from CircleCI's getting started doc. Once this starts building, I'll update the workflow to add scala/python tests

Added cicleci initial config

---

python/ml4ir/base/data/tfrecord_helper.py
python/ml4ir/base/data/tfrecord_writer.py
python/ml4ir/base/features/feature_config.py
python/notebooks/iris_write_tf_records_example.ipynb

This PR updates the code needed for writing TF records from csv to files. 
I started diving to the library trying to write tfrecords for the iris dataset (see notebook also). In this current version, the code has a few bugs that I try to fix here. Same for the notebook example PointwiseRankingDemo.ipynb that does not run anymore.
My idea, if these are merged, is to have few such notebook with public data that document the process. Also, my first PR to `ml4ir`!!

updates of tf-writer

---

python/ml4ir/applications/ranking/data/scripts/create_dataset.py
python/ml4ir/applications/ranking/model/ranking_model.py
python/ml4ir/applications/ranking/pipeline.py
python/ml4ir/applications/ranking/tests/test_base.py
python/ml4ir/applications/ranking/tests/test_create_dataset.py
python/ml4ir/applications/ranking/tests/test_feature_layer.py
python/ml4ir/applications/ranking/tests/test_losses.py
python/ml4ir/applications/ranking/tests/test_metrics.py
python/ml4ir/applications/ranking/tests/test_ranking_dataset.py
python/ml4ir/applications/ranking/tests/test_ranking_model.py
python/ml4ir/applications/ranking/tests/test_serving.py
python/ml4ir/base/config/keys.py
python/ml4ir/base/config/parse_args.py
python/ml4ir/base/data/csv_reader.py
python/ml4ir/base/data/relevance_dataset.py
python/ml4ir/base/data/tfrecord_reader.py
python/ml4ir/base/data/tfrecord_writer.py
python/ml4ir/base/features/feature_config.py
python/ml4ir/base/features/feature_fns/categorical.py
python/ml4ir/base/features/feature_fns/sequence.py
python/ml4ir/base/features/feature_layer.py
python/ml4ir/base/io/file_io.py
python/ml4ir/base/io/local_io.py
python/ml4ir/base/io/spark_io.py
python/ml4ir/base/model/relevance_model.py
python/ml4ir/base/model/scoring/interaction_model.py
python/ml4ir/base/model/scoring/scoring_model.py
python/ml4ir/base/pipeline.py
python/requirements.txt

The PR includes changes required to read the following:
- data (any directory -> copied over to local FS)
- feature config + model config (any YAML/JSON file)
- dataframe(eg: vocabulary files)
and writing the following back to HDFS:
- models
- logs, metrics, etc

Enabling Spark based HDFS I/O for running ml4ir @rev balikasg@

---

python/ml4ir/base/data/relevance_dataset.py
python/ml4ir/base/data/tfrecord_helper.py
python/ml4ir/base/data/tfrecord_reader.py

Improved training by 30% in one of my entity prediction test.

Add dataset prefetch to improve performance.

---

jvm/ml4ir-inference/src/main/scala/ml4ir/inference/tensorflow/data/FeaturesConfigHelper.scala
jvm/ml4ir-inference/src/main/scala/ml4ir/inference/tensorflow/data/ModelFeaturesConfig.scala
jvm/ml4ir-inference/src/test/java/ml4ir/inference/tensorflow/ExampleJavaBuilderTest.java
jvm/ml4ir-inference/src/test/resources/classification/feature_config_with_same_name.yaml
jvm/ml4ir-inference/src/test/scala/ml4ir/inference/tensorflow/TensorFlowInferenceTest.scala

This mismatch led to different prediction between java/scala and python

Fix mismatch between name node_name in FeatureConfig mapping.

---

python/README.md
python/requirements.txt

Keeping python library to minimum requirements.

Updating and cleaning python libraries

---

.circleci/config.yml
README.md
docs/source/index.rst
docs/source/installation/index.md
docs/source/misc/changelog.md
python/README.md
python/build-requirements.txt
python/requirements.txt
python/setup.py

- Removing unnecessary dependencies from base `requirements.txt`
- Adding a changelog for version management

Cleaning up base requirements.txt and adding changelog

---

docs/source/quickstart/model_config.md
python/ml4ir/applications/classification/tests/data/configs/model_config.yaml
python/ml4ir/applications/classification/tests/test_calibration.py
python/ml4ir/base/config/keys.py
python/ml4ir/base/model/calibration/temperature_scaling.py
python/ml4ir/base/model/relevance_model.py
python/ml4ir/base/pipeline.py

This PR is a **draft**  to add the learned temperature parameter to the model and save the model with temperature.

adding temperature scaling layer and saving the model with TS

---

README.md
jvm/ml4ir-inference/scripts/generate_model.sh
jvm/ml4ir-inference/src/test/integration/ml4ir/inference/tensorflow/TensorFlowInferenceIT.scala
python/ml4ir/applications/ranking/tests/data/configs/feature_config.yaml
python/ml4ir/base/io/local_io.py
python/ml4ir/base/model/relevance_model.py

Add a full end_to_end test for ranking pipeline. Train a model in
Python, run some predictions and verify that the jvm is returning the
same values

Add end_to_end ranking test

---

docs/source/misc/changelog.md
python/ml4ir/base/pipeline.py
python/setup.py

@W-9172445@
@rev jakemannix@
@rev balikasg@
@rev lastmansleeping@

W-9172445 Adding pre_processing_step

---

docs/source/misc/changelog.md
python/ml4ir/base/pipeline.py
python/setup.py

@W-9172445@
@rev lastmansleeping@

@W-9172445 Adding other data source as part of initialization

---

docs/source/misc/changelog.md
python/ml4ir/base/pipeline.py
python/setup.py

Adding post training step as part of the finish() method.
@W-9366739@
@rev jakemannix@
@rev lastmansleeping@

@W-9366739 Adding post training step.

---

docs/source/misc/changelog.md
python/ml4ir/applications/ranking/tests/data/configs/feature_config.yaml
python/ml4ir/base/data/tfrecord_reader.py
python/ml4ir/base/features/feature_config.py
python/setup.py

Merging `dev_tf27` with latest master.

Adding rank as default required field (#153)

---

python/ml4ir/base/model/scoring/interaction_model.py

This is useful when using layers in model config which deal with strings and not just numeric types

Support strings as interaction model output

---

python/ml4ir/base/stats/t_test.py

Fix division by zero in compute_groupwise_running_variance_for_metrics

Fix division by zero in evaluation

---

jvm/ml4ir-inference/pom.xml
jvm/pom.xml

Reverting this PR -> https://github.com/salesforce/ml4ir/pull/197

Reverting java11 upgrade from #197 back to java8

---

python/ml4ir/applications/ranking/features/feature_fns/normalization.py
python/ml4ir/applications/ranking/tests/test_feature_fns.py
python/ml4ir/base/features/feature_layer.py

PR to add theoretical_min-max normalization for ranking features.

Adding theoretical min max norm

---

python/ml4ir/applications/ranking/model/layers/rank_transform.py
python/ml4ir/base/features/feature_fns/robust_scaler_transform.py
python/ml4ir/base/features/feature_fns/sentence_transformers.py
python/ml4ir/base/features/feature_layer.py
python/ml4ir/base/model/layers/sentence_transformers.py
python/ml4ir/base/tests/test_sentence_transformers.py
python/requirements.txt

Adding `SentenceTransformerWithTokenizer` layer and feature transform which allows us to model sentence embeddings as part of the tensorflow graph along with the tokenizer.

Adding sentence transformer layer
